### ISSUE TITLE
getOne() does not work -> LanguageNotFoundException

### ISSUE THREAD

**Issue by morksinaanab** [bestboysmedialab/language-list#1]
the getOne() method doesn't work properly. 
I looked at the code and I think it is because of changing the string of the languagecode to upper, whereas the keys in (for instance the PHP version) are not in uppercase.
I changed the code and removed the mb_strtoupper and then in works.
Next to that I think in the hasOne method you are loading the locale data twice (in the method itself, and by calling has->).

I got it working in my local version for my situation, would you like me to add a pull request?

**Comment by volkeransmann** [comment]
Thanks!
